### ISSUE TITLE
Multiple module import errors (warc, six)

### ISSUE THREAD

**Issue by Kvik313** [ArchiveTeam/seesaw-kit#106]
I am currently using Warrior v3

The URLTeam 2 project is working, however the other ones such as Flickr, does not.

The error when selecting Flickr is:

>2018-11-17 15:14:06,182 - seesaw.warrior - DEBUG - Result of the install process: True 
> 2018-11-17 15:14:06,183 - seesaw.warrior - DEBUG - Clone project flickr /home/warrior/projects/flickr 
> 2018-11-17 15:14:06,191 - seesaw.warrior - DEBUG - Cloning version 7379806 
> 2018-11-17 15:14:06,224 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/flickr-7379806/pipeline.py 
> 2018-11-17 15:14:06,225 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection 
> 2018-11-17 15:14:06,225 - seesaw.warrior - DEBUG - Executing pipeline 
> 2018-11-17 15:14:06,414 - seesaw.warrior - ERROR - Error loading pipeline Traceback (most recent call last): File "<string>", line 26, in <module> ImportError: No module named 'warc' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project pipeline_path, {"downloader": self.downloader}) File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline exec(pipeline_str, local_context, global_context) File "<string>", line 28, in <module> Exception: Please install warc with 'pip install warc'. 
> 2018-11-17 15:14:06,415 - seesaw.warrior - WARNING - Project flickr did not install correctly and we're ignoring this problem.

With newsgrabber I get the error

>ImportError: No module named 'six' 2018-11-17 20:07:49,477 - seesaw.warrior - WARNING - Project newsgrabber did not install correctly and we're ignoring this problem.

With tindeck i get the error

> Exception: Please install warc with 'pip install warc --upgrade'. 2018-11-17 20:10:25,959 - seesaw.warrior - WARNING - Project tindeck did not install correctly and we're ignoring this problem.

Government ftp gives the error

> FileNotFoundError: [Errno 2] No such file or directory: '/data/data/projects/ftpdisco-1156c27/CheetoFTP/scanner.py' 2018-11-17 20:12:49,356 - seesaw.warrior - WARNING - Project ftpdisco did not install correctly and we're ignoring this problem.

**Comment by localleon** [comment]
The Github Project faces the same problem !

**Comment by Arkiver2** [comment]
This is for a very old project. I have no seen recent bug reports like this. Will consider this fixed.
