### ISSUE TITLE
Warrior won't start under VB 6.1

### ISSUE THREAD

**Issue by Travellingman** [ArchiveTeam/seesaw-kit#116]
I don't know enough to understand the problem.  This was a clean install of VB, and import of Warrior.  See attached.

![VirtualBox](https://user-images.githubusercontent.com/10464213/77820697-acc48180-7116-11ea-936a-d8cc8cc60bba.JPG)
![ArcheWarrior won't start](https://user-images.githubusercontent.com/10464213/77820698-adf5ae80-7116-11ea-91aa-9f0e049cd33b.JPG)

**Comment by chfoo** [comment]
I'm looking for info about this and it seems like the VirtualBox driver didn't install correctly? A forum post says to go to C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv, then right-click VBoxDrv.inf, and select Install. Then either reboot, or open a command prompt as administator, and run command 'sc.exe start vboxdrv'.

**Comment by djsmiley2k** [comment]
I've seen that error when upgrading and not rebooting - did you reboot after installing virtualbox?

**Comment by Travellingman** [comment]
@ djsmiley2k
Perhaps that was it.  I had removed VB and did a clean install, added the extensions, and did NOT reboot.  Got the failure.  VB didn't ask for a reboot.

Removed VB again, clean install + extensions, REBOOT, and now it works.  Thank you!
