### ISSUE TITLE
See percentage of completion of an item

### ISSUE THREAD

**Issue by albertopasqualetto** [ArchiveTeam/seesaw-kit#120]
It would be great to have an idea of how much time it will take to end an item.

**Comment by TomGlass** [comment]
Hello,

This can be hard to judge project to project. Some projects each item is much smaller, others the item can be several GB. I'm going to close this on that basis, but I admit it would be great sadly not feasible

**Comment by albertopasqualetto** [comment]
So, you are saying that the projects should give some info on how many pages will be downloaded?
