### ISSUE TITLE
Exception: No usable Wget+At found.

### ISSUE THREAD

**Issue by Jshanks** [ArchiveTeam/seesaw-kit#132]
Issue raised elsewhere, but posting here so it gets visibility.

https://github.com/ArchiveTeam/warrior-dockerfile/issues/70

"WARNING - Project reddit did not install correctly and we're ignoring this problem."

`2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)`
`2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Check project has update reddit`
`2023-04-18 15:58:50,305 - seesaw.warrior - DEBUG - git fetch`
`2023-04-18 15:58:50,637 - seesaw.warrior - DEBUG - False`
`2023-04-18 15:58:50,639 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit`
`2023-04-18 15:58:50,645 - seesaw.warrior - DEBUG - Cloning version 7f4db17`
`2023-04-18 15:58:50,646 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-7f4db17/pipeline.py`
`2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection`
`2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Executing pipeline`
`2023-04-18 15:58:50,666 - seesaw.warrior - ERROR - Error loading pipeline`
`Traceback (most recent call last):`
 ` File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project`
  `  (project, pipeline, config_values) = self.load_pipeline(`
  `File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline`
   ` exec(pipeline_str, local_context, global_context)`
  `File "<string>", line 56, in <module>`
`Exception: No usable Wget+At found.`
`2023-04-18 15:58:50,668 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.`

**Comment by TheTechRobo** [comment]
This is known. it's when a project is new but the Warrior has not been updated. 

It's possible there will be a solution in the future but for now, use another project until this one is fixed.

**Comment by tech234a** [comment]
The Reddit project should be fixed now.

**Comment by karmeleon** [comment]
Seeing this in a fully updated Docker image for `reddit` again, is there a known fix?

**Comment by Arkiver2** [comment]
We recently put minimum version checks in place for the Wget-AT version. I will consider this fixed.
