### ISSUE TITLE
Option to only download from sites with HTTPS and/or images

### ISSUE THREAD

**Issue by plonk420** [ArchiveTeam/seesaw-kit#98]
I have an ISP that'll inject HTML if someone gets a copyright strike (HTTP only, not HTTPS, and images are not affected, either). I want to contribute, but in that off chance that someone in the household gets a warning that it doesn't negatively impact the project. Is this a viable option?

**Comment by chfoo** [comment]
Seesaw doesn't control what a project's script will download so it can't really provide this option.

There is an open issue #28 that discusses implementing a full-featured check but it hasn't made any implementation progress yet.
